import type { Metadata } from "next";
import "./globals.css";

import SitePreviewLayout from "@/layouts/SitePreviewLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white">
        <SitePreviewLayout>{children}</SitePreviewLayout>
      </body>
    </html>
  );
}
